# This is a basic workflow to help you get started with Actions
name: automatic-update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 */4 * * *" #runs at 04:00 UTC everyday

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Same for every task/step 
    defaults:
        run:
            working-directory: ./assets/python
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      # Another job called     
      - name: Run update on rki data (legacy)
        run: python update_data.py
      - name: Run update on rki data
        run: python timeseries_data.py
      - name: Add & Commit
        uses: EndBug/add-and-commit@v5
        with:
           author_name: UpdateBot
           author_email: sebastian@mohrenclan.de
           message: "Updated rki dataset"
           add: 'assets/data/*'
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
